spring.application.name=cash_flow_spring_boot
# 1. Chave secreta de assinatura (Mínimo 32 caracteres)
app.jwt.secret=4a6a5a2e5c8b3d7f9e1a4c6d8f0b2e4a6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f

# 2. Tempo de vida do Token de Acesso (Ex: 24 horas = 86400000 ms)
app.jwt.expiration-ms=86400000

# 3. Tempo de vida do Refresh Token (Ex: 7 dias = 604800000 ms)
app.jwt.refresh-expiration-ms=604800000